version: 1
update_configs:
  - package_manager: "github_actions"
    directory: "/"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "monthly"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
